---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-volume
  namespace: airflow
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/airflow-logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
...
