apiVersion: v1
kind: Secret
metadata:
  name: example1
  namespace: airflow
type: Opaque
data:
  # echo -n 'This is a big secret' | base64 -w 0
  BIG_SECRET: VGhpcyBpcyBhIGJpZyBzZWNyZXQ=
  # echo -n 'mysql+mysqlconnector://airflow_test:airflow_test@10.0.2.2:3306/airflow_test' | base64 -w 0
  SQLALCHEMY_DATABASE_URI:
